version: "3.3"
  services:

    db:
      image: postgres:latest
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 1111
        POSTGRES_DB: netology_stocks_products
      ports:
        - "5432:5432"
      volumes:
        - ./pg-data:/var/lib/postgres/data

    django:
      build:
        context: ./django_app
        dockerfile: Dockerfile
      links:
        - db

    nginx:
      image: nginx:latest
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./default.conf:/etc/nginx/conf.d/default.conf
      links:
        - django

